services:
  - type: web
    name: inventory-api
    env: node
    plan: free
    rootDir: web-app/server
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: inventorydb
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: ALLOW_ADMIN_PASSWORD_CHANGE
        value: false
      - key: UNSPLASH_ACCESS_KEY
        sync: false
        optional: true
